### ISSUE TITLE
Compatibility with empty chapters

### ISSUE THREAD

**Issue by nagim** [cthos/atom-gitbook#59]
Hi,

Sorry to bug you again!
In GitBook (combined with the plugins `ungrey` and `toggle-chapters`), it is possible to define empty chapters in `SUMMARY.md` like this:

``` markdown
# Summary

* [Welcome](README.md)
* [Ascii](ascii.adoc)
   * [rST](sdk.rst)
* New Section 
   * [Chapter 1](chapter1.md)
```

In this way, we can create a chapter which acts like just a folder for other chapters.
But when I enable the ToC in atom, it removes the lines with no link syntax. Same thing if I change it back and force reload it, it overwrites the `SUMMARY.md` by removing that particular line(s).

Could you please check if you could make the plugin ignore the lines with no link syntax?

Thanks a lot!

Cheers,
Imre

**Comment by cthos** [comment]
Sure, I can see about ensuring it doesn't remove items when it persists the file. For showing them it sorta depends on how `gitbook-parsers` handles it for when I finally have time to work on #56.

**Comment by nagim** [comment]
Awesome, thanks a ton! :beers:

**Comment by cthos** [comment]
There's a branch up now `issue-56` which implements #56, that solves this problem...sort of... currently it still assumes that the file name should exist, so double clicking on the element and telling it to create the file will cause a :boom: .

Working on that. Also some weirdness in Linux with the drag + drop, but it seems mostly alright. I'll work on getting it stable in the next couple of days, but feel free to give it a shot if you want to try it out.

`apm rebuild` or `npm install` will probably be necessary as I added an npm module.

**Comment by nagim** [comment]
Thanks for working on this!
Yup, tested it, and it works, mostly.
Basically, if you don't poke around the ToC, just displaying it for reference, or opening files from it, it's fine.
As soon as you start drag+dropping chapters, it immediately creates a `new_section` folder and puts it in the summary like this:

Before:

``` markdown
* [Welcome](README.md)
* [Ascii](ascii.adoc)
   * [rST](sdk.rst)
* New Section 
   * [Chapter 1](chapter1.md)
```

After:

``` markdown
* [Welcome](welcome.md)
* [Ascii](ascii\README.md)
  * [rST](ascii\rst.md)
* [New Section](new_section\README.md)
  * [Chapter 1](new_section\chapter_1.md)
```

Note, that it also created a folder for the file named `ascii.adoc`, although it has a valid source file.
The resulting folders (`ascii` and `new_folder`) are empty, so I assume it will break the references.

Cheers,
Imre

**Comment by cthos** [comment]
The behaviour you're describing is actually expected, but there's a config setting to turn it off called "Reorder Files on Table of Contents Change". Let me know if turning that off doesn't disable that.

And the empty folders are fine, as soon as you double click on a reference it will ask you to create the file if it doesn't exist. (It should, however, move any files that already existed).

**Comment by cthos** [comment]
Another update, I pushed a few commits about this, now it won't write `(null)` after empty filenames and it'll properly not attempt to open the editor if you double click on it.

Outstanding thing:
1. The moving of files is based on the filename, and not any other kind of identifier, so I'll have to fix that. Hashing the name + the filename probably.

**Comment by nagim** [comment]
I tried to test it, but now the ToC won't show (empty). I thought it was that I had 2 projects open.
I removed one of them, but still not showing.

Tried Add as a chapter function, following error:

```
Uncaught TypeError: Cannot read property 'length' of undefined
.atom/packages/atom-gitbook/lib/helper/summary-parser.coffee:88
Hide Stack Trace
TypeError: Cannot read property 'length' of undefined
    at SummaryParser.module.exports.SummaryParser.addSection (file:///C:/Users/.atom/packages/atom-gitbook/lib/helper/summary-parser.coffee:64:51)
    at Object.module.exports.addFileAsChapter (file:///C:/Users/.atom/packages/atom-gitbook/lib/main.coffee:99:12)
    at HTMLOListElement.subscriptions.add.atom.commands.add.atom-gitbook:add-file-as-chapter (file:///C:/Users/.atom/packages/atom-gitbook/lib/main.coffee:52:106)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\AppData\Local\atom\app-1.5.3\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\AppData\Local\atom\app-1.5.3\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\AppData\Local\atom\app-1.5.3\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\AppData\Local\atom\app-1.5.3\resources\app.asar\src\atom-environment.js:1019:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (C:\Users\AppData\Local\atom\app-1.5.3\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\AppData\Local\atom\app-1.5.3\resources\atom.asar\renderer\api\lib\remote.js:143:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\AppData\Local\atom\app-1.5.3\resources\app.asar\src\context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (C:\Users\AppData\Local\atom\app-1.5.3\resources\app.asar\src\window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (C:\Users\AppData\Local\atom\app-1.5.3\resources\app.asar\src\window-event-handler.js:3:61)
```

Tried to force reload ToC, following error:

```
Uncaught TypeError: Cannot read property 'length' of undefined
.atom/packages/atom-gitbook/lib/helper/summary-parser.coffee:189
Hide Stack Trace
TypeError: Cannot read property 'length' of undefined
    at SummaryParser.module.exports.SummaryParser.organizeFilesFromTree (file:///C:/Users/.atom/packages/atom-gitbook/lib/helper/summary-parser.coffee:135:5)
    at NavigationPane.module.exports.NavigationPane.refresh (file:///C:/Users/.atom/packages/atom-gitbook/lib/nav-pane.coffee:31:18)
    at AtomGitbookView.module.exports.AtomGitbookView.refresh (file:///C:/Users/.atom/packages/atom-gitbook/lib/atom-gitbook-view.coffee:22:14)
    at Object.module.exports.forceReloadToC (file:///C:/Users/.atom/packages/atom-gitbook/lib/main.coffee:136:19)
    at atom-workspace.subscriptions.add.atom.commands.add.atom-gitbook:force-reload-toc (file:///C:/Users/.atom/packages/atom-gitbook/lib/main.coffee:48:97)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\AppData\Local\atom\app-1.5.3\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\AppData\Local\atom\app-1.5.3\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\AppData\Local\atom\app-1.5.3\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\AppData\Local\atom\app-1.5.3\resources\app.asar\src\atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

Thanks!

**Comment by cthos** [comment]
@nagim - Is this using the same summary file earlier in the issue thread or a different one?

**Comment by nagim** [comment]
No, it's another one:

``` asciidoc
= Summary

. link:README.adoc[Welcome]
```

Shouldn't be a problem with it.

**Comment by cthos** [comment]
Hmmm, that's odd. I'll have a look.

**Comment by cthos** [comment]
Hmm, the adoc file is working for me.

![image](https://cloud.githubusercontent.com/assets/456545/13447726/922b71fa-dfd2-11e5-9022-589a253c80d3.png)

I'm using `book.json` to point directly at the `summary.adoc` file there, and it appears to load okay. Can you give me any more information on the issue?

There is still a secondary issue with Adding as chapter, in that it assumes the file is a markdown file and formats the output accordingly which is a problem. I think I'll open up a second issue for that and merge in #56.

**Comment by nagim** [comment]
Hi,

Thanks a lot for the efforts!
I've not had the time to test it out fully, but I will.

However, I noticed that the "Insert as a GitBook include" function (which
is very handy, by the way), inserts include path with wrong slashes.

{% include "....\ instead of {% include "../../ which causes builds to
fail (online). Also, absolute paths might be more useful, if we move around
the doc files, it wouldn't break the reference to the includes.

Thanks again!

Cheers,
Imre
​

**Comment by cthos** [comment]
Hmm, are you on Windows? The paths are just generated from whatever Atom reports the path to the file is:
https://github.com/cthos/atom-gitbook/blob/master/lib/main.coffee#L119

Should be relatively easy to normalize those to forward slashes.

As for the relative path, that's there because the absolute path would need to be normalized from the project root, right?

**Comment by nagim** [comment]
Yes, forgot to mention, I'm on Windows. I think it should be fixed to
forward slash, because GitBook won't accept anything else, regardless of
the used OS.

Well, for GitBook, absolute paths are resolved to the project folder, so
instead of {% include "../../Includes/test.adoc" %}, {% include
"/Includes/test.adoc" %}  will always work.

Cheers,
Imre

2016-04-01 2:01 GMT+02:00 Alexander Ward notifications@github.com:

**Comment by cthos** [comment]
@nagim - Sorry for the delay, been pretty busy. #66 _should_ fix the issue for inserts.

**Comment by cthos** [comment]
I also merged the other PR into master.

I'm going to close this issue, feel free to continue to comment or open another issue for anything else you need.

**Comment by nagim** [comment]
Thanks a lot for all the effort. The insert as include is pretty sweet, I use it all the time.
BTW, I tried to test all the previous updates, but the ToC just didn't load somehow.
It turns out that the key is to explicitly point to the summary file in `book.json`.
Now it loads and displays fine.

Cheers,
Imre

**Comment by cthos** [comment]
Thanks! Made #69 to track that, not sure when I'll have a chance to get to it though. I'll shoot for Sunday or Monday night.
